# Generated by Django 3.0.5 on 2021-01-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_ID', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=20, verbose_name='Job Title')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
