# Generated by Django 3.0.5 on 2021-01-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisal', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appraisal.manager'),
        ),
    ]
