# Generated by Django 3.0.5 on 2021-01-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('manager_ID', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=30, verbose_name='manager name')),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('appraisal_ID', models.AutoField(primary_key=True, serialize=False)),
                ('objective', models.CharField(max_length=40, verbose_name='objective')),
                ('year', models.CharField(max_length=4, verbose_name='year')),
                ('rating', models.IntegerField()),
                ('department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.Department')),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Employee')),
            ],
            options={
                'verbose_name': 'Appraisal',
                'verbose_name_plural': 'Appraisals',
            },
        ),
    ]
